package wingworld

type Flight struct {
	ExTrack               int         `json:"ex_track"`
	BookingStatus         interface{} `json:"bookingStatus"`
	FlightNo              string      `json:"flightNo"`
	DepartDate            string      `json:"departDate"`
	DepartTime            string      `json:"departTime"`
	DepartCityCode        interface{} `json:"departCityCode"`
	DepartCityName        interface{} `json:"departCityName"`
	DepartAirportCode     string      `json:"departAirportCode"`
	DepartAirportName     string      `json:"departAirportName"`
	DepartAirportTerminal interface{} `json:"departAirportTerminal"`
	ArriveCityCode        interface{} `json:"arriveCityCode"`
	ArriveCityName        interface{} `json:"arriveCityName"`
	ArriveDate            interface{} `json:"arriveDate"`
	ArriveTime            string      `json:"arriveTime"`
	ArriveAirportCode     string      `json:"arriveAirportCode"`
	ArriveAirportName     string      `json:"arriveAirportName"`
	ArriveAirportTerminal string      `json:"arriveAirportTerminal"`
	CrossDay              int         `json:"crossDay"`
	CraftType             string      `json:"craftType"`
	AirlineCode           string      `json:"airlineCode"`
	AirlineName           string      `json:"airlineName"`
	Duration              string      `json:"duration"`
	IsShare               int         `json:"isShare"`
	ShareFlightNo         interface{} `json:"shareFlightNo"`
	ShareAirline          interface{} `json:"shareAirline"`
	ShareAirlineName      interface{} `json:"shareAirlineName"`
	MealFlag              interface{} `json:"mealFlag"`
	Meal                  interface{} `json:"meal"`
	StopInformation       interface{} `json:"stopInformation"`
	StopNum               string      `json:"stopNum"`
	OnTimeRate            interface{} `json:"onTimeRate"`
	CarrierLogo           interface{} `json:"carrierLogo"`
	Correct               interface{} `json:"correct"`
	LowCabin              Cabin       `json:"lowCabin"`
	ExtInfo               interface{} `json:"extInfo"`
	AdultTgqRule          interface{} `json:"adultTgqRule"`
	ChildTgqRule          interface{} `json:"childTgqRule"`
	BaggageRuleInfo       interface{} `json:"baggageRuleInfo"`
	SpecialProductRule    interface{} `json:"specialProductRule"`
}

type Cabin struct {
	SessionID                  interface{} `json:"sessionId"`
	BusinessExt                interface{} `json:"businessExt"`
	CabinClass                 string      `json:"cabinClass"`
	CabinClassName             string      `json:"cabinClassName"`
	CabinCode                  string      `json:"cabinCode"`
	CabinName                  interface{} `json:"cabinName"`
	ChdCabinCode               interface{} `json:"chdCabinCode"`
	SeatNum                    interface{} `json:"seatNum"`
	CabinPrice                 interface{} `json:"cabinPrice"`
	CabinClassFullPrice        interface{} `json:"cabinClassFullPrice"`
	Discount                   float64     `json:"discount"`
	MajorCode                  interface{} `json:"majorCode"`
	FreeLuggage                interface{} `json:"freeLuggage"`
	FreeLuggageUnit            interface{} `json:"freeLuggageUnit"`
	OverloadLuggage            interface{} `json:"overloadLuggage"`
	BillType                   interface{} `json:"billType"`
	BillTypeDesc               interface{} `json:"billTypeDesc"`
	ApplicableTravelerCategory interface{} `json:"applicableTravelerCategory"`
	PriceInfo                  interface{} `json:"priceInfo"`
	Policy                     interface{} `json:"policy"`
	Time                       interface{} `json:"time"`
	TicketTime                 interface{} `json:"ticketTime"`
	OutSessionID               interface{} `json:"outSessionId"`
	FilghtSessionID            interface{} `json:"filghtSessionId"`
	WrapperID                  interface{} `json:"wrapperId"`
	Domain                     interface{} `json:"domain"`
	Tgq                        interface{} `json:"tgq"`
	Baggagerule                interface{} `json:"baggagerule"`
	GroupID                    interface{} `json:"groupId"`
	AirlineCode                interface{} `json:"airlineCode"`
	AirlineName                interface{} `json:"airlineName"`
	FlightNo                   interface{} `json:"flightNo"`
	DepartDate                 interface{} `json:"departDate"`
	DepartCityCode             interface{} `json:"departCityCode"`
	ArriveCityCode             interface{} `json:"arriveCityCode"`
	AdtPrice                   interface{} `json:"adtPrice"`
	ChdPrice                   interface{} `json:"chdPrice"`
	ProductID                  interface{} `json:"productId"`
	BookingTag                 interface{} `json:"bookingTag"`
	FacePrice                  interface{} `json:"facePrice"`
}
